// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oxyHubRazor.Data;

namespace oxyHubRazor.Migrations
{
    [DbContext(typeof(oxyHubRazorContext))]
    [Migration("20210107131851_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("oxyHubRazor.Models.mqttData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("airQuality")
                        .HasColumnType("int");

                    b.Property<int>("airQualityPrecision")
                        .HasColumnType("int");

                    b.Property<int>("eco2")
                        .HasColumnType("int");

                    b.Property<int>("feuchtigkeit")
                        .HasColumnType("int");

                    b.Property<int>("rawEthanol")
                        .HasColumnType("int");

                    b.Property<int>("rawh2")
                        .HasColumnType("int");

                    b.Property<int>("temperatur")
                        .HasColumnType("int");

                    b.Property<int>("tvoc")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("mqttData");
                });
#pragma warning restore 612, 618
        }
    }
}
